[DEFAULT]
repo = lite-utils
lib_name = %(repo)s
min_python = 3.11
version = 0.0.10
license = apache2
black_formatting = False

### nbdev ###
doc_path = _docs
branch = main
lib_path = lite_utils
nbs_path = nbs
recursive = True
tst_flags = notest
put_version_in_init = True
user = ssslakter
author = ssslakter

### Optional ###
# requirements = fastcore pandas
# dev_requirements = 
# console_scripts =
# conda_user = 
# package_data =